networks:
  showcase:
    external: true

services:
  nginx:
    container_name: ${NGINX_CONTAINER}
    build: nginx
    ports:
      - '${NGINX_HTTP_PORT}'
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - kotlin
    environment:
      - APP_NAME=${APP_NAME}
      - SERVER_NAME=${SERVER_NAME}
      - APP_PATH=${APP_PATH}
      - VIRTUAL_HOST=${SERVER_NAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SERVER_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - CERT_NAME=default
      - HTTPS_METHOD=noredirect
    networks:
      - showcase

  kotlin:
    container_name: ${KOTLIN_CONTAINER}
    build: java
    ports:
      - '${KOTLIN_DEBUG_PORT}:5005'
    volumes:
      - ./../../../backends/kotlin-ktor:/var/www/${APP_NAME}
      - kotlin_build:/var/www/${APP_NAME}/build
      - kotlin_gradle:/var/www/${APP_NAME}/.gradle
      - kotlin_kotlin:/var/www/${APP_NAME}/.kotlin
    working_dir: /var/www/${APP_NAME}
    command: gradle run
    networks:
      - showcase

volumes:
  kotlin_build:
  kotlin_gradle:
  kotlin_kotlin:
