networks:
  showcase:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ${NGINX_CONTAINER}
    environment:
      - 'DHPARAM_GENERATION=false'
    ports:
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - showcase

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT_CONTAINER}
    environment:
      - NGINX_PROXY_CONTAINER=${NGINX_CONTAINER}
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - showcase
