networks:
  showcase:
    external: true

services:
  nginx:
    container_name: ${NGINX_CONTAINER}
    build: nginx
    ports:
      - '${NGINX_HTTP_PORT}'
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - rb-rails
    environment:
      - APP_NAME=${APP_NAME}
      - SERVER_NAME=${SERVER_NAME}
      - APP_PATH=${APP_PATH}
      - VIRTUAL_HOST=${SERVER_NAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${SERVER_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - CERT_NAME=default
      - HTTPS_METHOD=noredirect
    networks:
      - showcase

  rb-rails:
    container_name: ${RB_RAILS_CONTAINER}
    build: ruby
    ports:
      - '${RB_RAILS_DEBUG_PORT}:1234'
    volumes:
      - ./../../../backends/ruby-rails:/var/www/${APP_NAME}
    working_dir: /var/www/${APP_NAME}
    command: >
      sh -c "bundle install --quiet &&
             bundle exec puma -b tcp://0.0.0.0:3000"
    networks:
      - showcase
